require 'kraken_client'

# YOU MUST SET ENVIRONMENT VARIABLES KRAKEN_API_KEY AND
# KRAKEN_API_SECRET TO TEST PRIVATE DATA QUERIES. PRIVATE
# TESTS WILL FAIL OTHERWISE.

API_KEY    = ENV['KRAKEN_API_KEY']
API_SECRET = ENV['KRAKEN_API_SECRET']